export const ENABLE_LOADER = 'ENABLE_LOADER'
export const DISABLE_LOADER = 'DISABLE_LOADER'

export const LOGIN_REQUEST_WITHOUT_PARAMTER = 'LOGIN_REQUEST_WITHOUT_PARAMTER'
export const LOGIN_RESPONSE_WITHOUT_PARAMTER_SUCCESS =
  'LOGIN_RESPONSE_WITHOUT_PARAMTER_SUCCESS'
export const LOGIN_RESPONSE_WITHOUT_PARAMTER_FAILURE =
  'LOGIN_RESPONSE_WITHOUT_PARAMTER_FAILURE'

export const LOGIN_REQUEST_WITH_PARAMTER = 'LOGIN_REQUEST_WITH_PARAMTER'
export const LOGIN_RESPONSE_WITH_PARAMTER_SUCCESS =
  'LOGIN_RESPONSE_WITH_PARAMTER'
export const LOGIN_RESPONSE_WITH_PARAMTER_FAILURE =
  'LOGIN_RESPONSE_WITH_PARAMTER_FAILURE'

export const REQUEST_LOGIN_CHECK = 'REQUEST_LOGIN_CHECK'
export const LOGIN_CHECK_SUCCESS = 'LOGIN_CHECK_SUCCESS'
export const LOGIN_CHECK_FAILURE = 'LOGIN_CHECK_FAILURE'

export const SERVICE_SPLASH_RESET = 'SERVICE_SPLASH_RESET'

export const REQUEST_LOGIN_STATUS = 'REQUEST_LOGIN_STATUS'
export const LOGIN_STATUS_SUCCESS = 'LOGIN_STATUS_SUCCESS'
export const LOGIN_STATUS_FAILURE = 'LOGIN_STATUS_FAILURE'

export const REQUEST_MANUAL_STATUS = 'REQUEST_MANUAL_STATUS'
export const REQUEST_STATUS = 'REQUEST_STATUS'
export const STATUS_RESPONSE_SUCCESS = 'STATUS_RESPONSE_SUCCESS'
export const STATUS_RESPONSE_FAILURE = 'STATUS_RESPONSE_FAILURE'

//##################
export const SPLASH_GENERATE_QR_CODE_REQUEST = 'SPLASH_GENERATE_QR_CODE_REQUEST'
export const SPLASH_GENERATE_QR_CODE_RESPONSE_SUCESS =
  'SPLASH_GENERATE_QR_CODE_RESPONSE_SUCESS'
export const SPLASH_GENERATE_QR_CODE_RESPONSE_FAILURE =
  'SPLASH_GENERATE_QR_CODE_RESPONSE_FAILURE'

//##################
export const SPLASH_CONNECTIVITY_REQUEST = 'SPLASH_CONNECTIVITY_REQUEST'
export const SPLASH_CONNECTIVITY_RESPONSE_SUCESS =
  'SPLASH_CONNECTIVITY_RESPONSE_SUCESS'
export const SPLASH_CONNECTIVITY_RESPONSE_FAILURE =
  'SPLASH_CONNECTIVITY_RESPONSE_FAILURE'

//##################
export const SPLASH_INCREMENT_REQUEST = 'SPLASH_INCREMENT_REQUEST'

//##################
export const SPLASH_END_REQUEST = 'SPLASH_END_REQUEST'

export const SET_API_TOKEN = 'SET_API_TOKEN'

export const NOTIFICATION_BINDING_REQUEST = 'NOTIFICATION_BINDING_REQUEST'
export const NOTIFICATION_BINDING_SUCCESS = 'NOTIFICATION_BINDING_SUCCESS'
export const NOTIFICATION_BINDING_FAIL = 'NOTIFICATION_BINDING_FAIL'
